//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace TeststingDotNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        [Required]
        [Range(1,5,ErrorMessage="The number of adults is not valid.")]
        public int Adults { get; set; }
        [Range(0, 6, ErrorMessage = "The number of children is not valid.")]
        public int Children { get; set; }
        
        public int RoomBooking { get; set; }
        [Required(ErrorMessage="*")]
        public string Nume { get; set; }
        [Required(ErrorMessage = "*")]
        public string Prenume { get; set; }
        [Required]
        [DataType(DataType.EmailAddress,ErrorMessage="Invalid email address")]
        public string E_Mail { get; set; }
        [Required]
        public long Telefon { get; set; }
        [Required]
        [DataType(DataType.Date, ErrorMessage = "Invalid date format")]
        public string DateStart { get; set; }
        [Required]
        [DataType(DataType.Date, ErrorMessage = "Invalid date format")]
        public string DateStop { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
